#!/usr/bin/env bash
# prepare.sh - fetch pinned OpenWrt, install feeds, apply our layer.
#
# Usage:  scripts/prepare.sh
# Env:    FLAVOR=full|base   (default: full; full = base.config + performance.config)
#         WORK_DIR=<path>    (default: work/openwrt, relative to repo root)
#
# Idempotent: re-running reuses an existing, correct checkout. It never
# deletes an existing checkout that does not match the pinned commit.
set -euo pipefail

# ---- Pinned upstream (DO NOT loosen) -----------------------------------------
OPENWRT_VERSION="25.12.2"
OPENWRT_TAG="v${OPENWRT_VERSION}"
OPENWRT_COMMIT="d266501ad6188cce279a487b1ce61f4f327cd496"
OPENWRT_REPO="https://github.com/openwrt/openwrt.git"
# KERNEL_PATCHVER of ramips at the pinned tag (target/linux/ramips/Makefile).
# Only used to route patches/kernel/*.patch to the right directory.
KERNEL_PATCHVER="6.12"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="${WORK_DIR:-${REPO_ROOT}/work/openwrt}"
FLAVOR="${FLAVOR:-full}"
META_DIR="${WORK_DIR}/.."   # build metadata lands next to the buildroot

log() { printf '==> %s\n' "$*"; }

# ---- 1. Obtain pinned OpenWrt -------------------------------------------------
if [ -d "${WORK_DIR}/.git" ]; then
    HEAD_NOW="$(git -C "${WORK_DIR}" rev-parse HEAD)"
    if [ "${HEAD_NOW}" != "${OPENWRT_COMMIT}" ]; then
        echo "ERROR: ${WORK_DIR} exists but HEAD=${HEAD_NOW}, expected ${OPENWRT_COMMIT} (${OPENWRT_TAG})." >&2
        echo "       Refusing to modify an unexpected checkout. Move it away or fix it manually." >&2
        exit 1
    fi
    log "OpenWrt checkout present at pinned commit, reusing"
else
    log "Cloning OpenWrt ${OPENWRT_TAG} (shallow)"
    git clone --depth 1 --branch "${OPENWRT_TAG}" "${OPENWRT_REPO}" "${WORK_DIR}"
fi

# ---- 2. Verify upstream revision ----------------------------------------------
HEAD_NOW="$(git -C "${WORK_DIR}" rev-parse HEAD)"
if [ "${HEAD_NOW}" != "${OPENWRT_COMMIT}" ]; then
    echo "ERROR: upstream revision mismatch: got ${HEAD_NOW}, expected ${OPENWRT_COMMIT}" >&2
    exit 1
fi
log "Upstream verified: ${OPENWRT_TAG} = ${OPENWRT_COMMIT}"

# ---- 3. Feeds (pinned by the tag's feeds.conf.default to exact commits) --------
log "Updating + installing feeds"
"${WORK_DIR}/scripts/feeds" update -a
"${WORK_DIR}/scripts/feeds" install -a

# ---- 4. Build metadata ---------------------------------------------------------
{
    echo "openwrt_version=${OPENWRT_VERSION}"
    echo "openwrt_tag=${OPENWRT_TAG}"
    echo "openwrt_commit=${OPENWRT_COMMIT}"
    echo "flavor=${FLAVOR}"
    for f in packages luci routing telephony video; do
        if [ -d "${WORK_DIR}/feeds/${f}/.git" ]; then
            echo "feed_${f}=$(git -C "${WORK_DIR}/feeds/${f}" rev-parse HEAD)"
        fi
    done
    echo "prepare_date_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "${META_DIR}/build-metadata.txt"
log "Build metadata written"

# ---- 5. Configuration -----------------------------------------------------------
if [ "${FLAVOR}" != "base" ] && [ "${FLAVOR}" != "full" ]; then
    echo "ERROR: FLAVOR must be 'base' or 'full' (got '${FLAVOR}')" >&2
    exit 1
fi
{
    echo "# flavor=${FLAVOR} - generated by scripts/prepare.sh"
    cat "${REPO_ROOT}/config/base.config"
    if [ "${FLAVOR}" = "full" ]; then
        cat "${REPO_ROOT}/config/performance.config"
    fi
} > "${WORK_DIR}/.config"
log "Config seed installed (${FLAVOR}); defconfig runs in build.sh"

# ---- 6. Custom files overlay -----------------------------------------------------
if [ -n "$(ls -A "${REPO_ROOT}/files" 2>/dev/null)" ]; then
    mkdir -p "${WORK_DIR}/files"
    cp -a "${REPO_ROOT}/files/." "${WORK_DIR}/files/"
    log "Custom files overlay applied (files/ -> image rootfs)"
fi

# ---- 7. Patches (convention; no-op while the patch dirs are empty/absent) --------
#   patches/openwrt/*.patch              -> git apply at buildroot root
#   patches/kernel/*.patch               -> target/linux/ramips/patches-${KERNEL_PATCHVER}/
#   patches/packages/<feed>/<pkg>/*.patch -> feeds/<feed>/<pkg>/patches/
shopt -s nullglob
for p in "${REPO_ROOT}"/patches/openwrt/*.patch; do
    log "Applying buildroot patch: $(basename "$p")"
    git -C "${WORK_DIR}" apply --check "$p"
    git -C "${WORK_DIR}" apply "$p"
done
KDEST="${WORK_DIR}/target/linux/ramips/patches-${KERNEL_PATCHVER}"
for p in "${REPO_ROOT}"/patches/kernel/*.patch; do
    [ -d "${KDEST}" ] || { echo "ERROR: ${KDEST} missing"; exit 1; }
    log "Staging kernel patch: $(basename "$p")"
    cp "$p" "${KDEST}/"
done
for d in "${REPO_ROOT}"/patches/packages/*/*/; do
    [ -d "$d" ] || continue
    feed="$(basename "$(dirname "$d")")"; pkg="$(basename "$d")"
    dest="${WORK_DIR}/feeds/${feed}/${pkg}/patches"
    [ -d "${WORK_DIR}/feeds/${feed}/${pkg}" ] || { echo "ERROR: feeds/${feed}/${pkg} missing"; exit 1; }
    mkdir -p "$dest"
    for p in "$d"*.patch; do
        log "Staging package patch feeds/${feed}/${pkg}: $(basename "$p")"
        cp "$p" "$dest/"
    done
done

log "prepare.sh done (flavor=${FLAVOR})"
