#!/usr/bin/env bash
# prepare.sh - fetch pinned OpenWrt, install feeds, apply our source layer.
# Used by the source-build pipeline (full Buildroot). User-facing package-set
# variants (base/full) are built by the ImageBuilder pipeline instead - this
# repo deliberately does not compile two source flavors.
#
# Usage:  scripts/prepare.sh
# Env:    WORK_DIR=<path>    (default: work/openwrt, relative to repo root)
#
# Idempotent: re-running reuses an existing, correct checkout. It never
# deletes an existing checkout that does not match the pinned commit.
set -euo pipefail

# ---- Pinned upstream (DO NOT loosen) -----------------------------------------
OPENWRT_VERSION="25.12.5"
OPENWRT_TAG="v${OPENWRT_VERSION}"
OPENWRT_COMMIT="f0a60eee2fe051741c643ea6118718aae1ef17fb"
OPENWRT_REPO="https://github.com/openwrt/openwrt.git"
# KERNEL_PATCHVER of ramips at the pinned tag (target/linux/ramips/Makefile).
# Only used to route patches/kernel/*.patch to the right directory.
KERNEL_PATCHVER="6.12"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="${WORK_DIR:-${REPO_ROOT}/work/openwrt}"
META_DIR="${WORK_DIR}/.."   # build metadata lands next to the buildroot

log() { printf '[%s] ==> %s\n' "$(date -u +%H:%M:%SZ)" "$*"; }

# ---- 1. Obtain pinned OpenWrt -------------------------------------------------
if [ -d "${WORK_DIR}/.git" ]; then
    HEAD_NOW="$(git -C "${WORK_DIR}" rev-parse HEAD)"
    if [ "${HEAD_NOW}" != "${OPENWRT_COMMIT}" ]; then
        echo "ERROR: ${WORK_DIR} exists but HEAD=${HEAD_NOW}, expected ${OPENWRT_COMMIT} (${OPENWRT_TAG})." >&2
        echo "       Refusing to modify an unexpected checkout. Move it away or fix it manually." >&2
        exit 1
    fi
    log "OpenWrt checkout present at pinned commit, reusing"
else
    if [ -e "${WORK_DIR}" ] && [ -n "$(ls -A "${WORK_DIR}" 2>/dev/null)" ]; then
        echo "ERROR: ${WORK_DIR} exists, is not empty, and is not a git checkout." >&2
        echo "       A cache (dl/, .ccache/) must be restored AFTER this script, not before" >&2
        echo "       (CI run 35453035164 failed here with git exit 128). Otherwise move the" >&2
        echo "       stale directory away manually; prepare.sh never deletes unexpected content." >&2
        exit 1
    fi
    log "Cloning OpenWrt ${OPENWRT_TAG} (shallow)"
    git clone --depth 1 --branch "${OPENWRT_TAG}" "${OPENWRT_REPO}" "${WORK_DIR}"
fi

# ---- 2. Verify upstream revision ----------------------------------------------
HEAD_NOW="$(git -C "${WORK_DIR}" rev-parse HEAD)"
if [ "${HEAD_NOW}" != "${OPENWRT_COMMIT}" ]; then
    echo "ERROR: upstream revision mismatch: got ${HEAD_NOW}, expected ${OPENWRT_COMMIT}" >&2
    exit 1
fi
log "Upstream verified: ${OPENWRT_TAG} = ${OPENWRT_COMMIT}"

# ---- 3. Feeds (pinned by the tag's feeds.conf.default to exact commits) --------
log "Updating + installing feeds"
"${WORK_DIR}/scripts/feeds" update -a
"${WORK_DIR}/scripts/feeds" install -a

# ---- 4. Build metadata ---------------------------------------------------------
{
    echo "pipeline=source-build"
    echo "openwrt_version=${OPENWRT_VERSION}"
    echo "openwrt_tag=${OPENWRT_TAG}"
    echo "openwrt_commit=${OPENWRT_COMMIT}"
    echo "config_seed=config/base.config (canonical source config)"
    for f in packages luci routing telephony video; do
        if [ -d "${WORK_DIR}/feeds/${f}/.git" ]; then
            echo "feed_${f}=$(git -C "${WORK_DIR}/feeds/${f}" rev-parse HEAD)"
        fi
    done
    echo "prepare_date_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "${META_DIR}/build-metadata.txt"
log "Build metadata written"

# ---- 5. Configuration (canonical source config) ----------------------------------
{
    echo "# canonical source config - generated by scripts/prepare.sh"
    cat "${REPO_ROOT}/config/base.config"
} > "${WORK_DIR}/.config"
log "Config seed installed (config/base.config); defconfig runs in the build stage"

# ---- 6. Custom files overlay -----------------------------------------------------
if [ -n "$(ls -A "${REPO_ROOT}/files" 2>/dev/null)" ]; then
    mkdir -p "${WORK_DIR}/files"
    cp -a "${REPO_ROOT}/files/." "${WORK_DIR}/files/"
    log "Custom files overlay applied (files/ -> image rootfs)"
fi

# ---- 7. Patches (convention; no-op while the patch dirs are empty/absent) --------
#   patches/openwrt/*.patch              -> git apply at buildroot root
#   patches/kernel/*.patch               -> target/linux/ramips/patches-${KERNEL_PATCHVER}/
#   patches/packages/<feed>/<pkg>/*.patch -> feeds/<feed>/<pkg>/patches/
shopt -s nullglob
for p in "${REPO_ROOT}"/patches/openwrt/*.patch; do
    log "Applying buildroot patch: $(basename "$p")"
    git -C "${WORK_DIR}" apply --check "$p"
    git -C "${WORK_DIR}" apply "$p"
done
KDEST="${WORK_DIR}/target/linux/ramips/patches-${KERNEL_PATCHVER}"
for p in "${REPO_ROOT}"/patches/kernel/*.patch; do
    [ -d "${KDEST}" ] || { echo "ERROR: ${KDEST} missing"; exit 1; }
    log "Staging kernel patch: $(basename "$p")"
    cp "$p" "${KDEST}/"
done
for d in "${REPO_ROOT}"/patches/packages/*/*/; do
    [ -d "$d" ] || continue
    feed="$(basename "$(dirname "$d")")"; pkg="$(basename "$d")"
    dest="${WORK_DIR}/feeds/${feed}/${pkg}/patches"
    [ -d "${WORK_DIR}/feeds/${feed}/${pkg}" ] || { echo "ERROR: feeds/${feed}/${pkg} missing"; exit 1; }
    mkdir -p "$dest"
    for p in "$d"*.patch; do
        log "Staging package patch feeds/${feed}/${pkg}: $(basename "$p")"
        cp "$p" "$dest/"
    done
done

log "prepare.sh done"
